
-- Create the payments table to store M-Pesa transaction data
CREATE TABLE IF NOT EXISTS public.payments (
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    merchant_request_id text NULL,
    checkout_request_id text NULL,
    result_code integer NULL,
    result_desc text NULL,
    amount numeric NULL,
    mpesa_receipt_number text NULL,
    transaction_date timestamp with time zone NULL,
    phone_number text NULL,
    raw_payload jsonb NULL,
    CONSTRAINT payments_pkey PRIMARY KEY (id)
);

-- Enable Row-Level Security for the new table
ALTER TABLE public.payments ENABLE ROW LEVEL SECURITY;

-- Create policies for the payments table
-- Allow service_role to perform all actions
CREATE POLICY "Allow full access to service_role"
    ON public.payments
    AS PERMISSIVE
    FOR ALL
    TO service_role
    USING (true)
    WITH CHECK (true);

-- Allow authenticated users to read their own payments (optional, for future use)
CREATE POLICY "Allow individual user read access"
    ON public.payments
    AS PERMISSIVE
    FOR SELECT
    TO authenticated
    USING ((auth.uid() IN ( SELECT profiles.id
   FROM profiles
  WHERE (profiles.phone_number = payments.phone_number))));

-- Allow admin users to read all payments (assuming an 'admin' role exists)
CREATE POLICY "Allow admin read access"
    ON public.payments
    AS PERMISSIVE
    FOR SELECT
    TO service_role
    USING (true);
