-- Create a user-defined type for the status column
CREATE TYPE public.confirmation_status AS ENUM (
    'pending',
    'verified',
    'invalid'
);

-- Create the table to store manual payment confirmation submissions
CREATE TABLE IF NOT EXISTS public.payment_confirmations (
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    mpesa_code text NOT NULL,
    customer_name text NOT NULL,
    customer_phone text NOT NULL,
    amount numeric NOT NULL,
    payment_time text NOT NULL,
    status public.confirmation_status NOT NULL DEFAULT 'pending',
    CONSTRAINT payment_confirmations_pkey PRIMARY KEY (id),
    CONSTRAINT payment_confirmations_mpesa_code_key UNIQUE (mpesa_code)
);

-- Enable Row-Level Security
ALTER TABLE public.payment_confirmations ENABLE ROW LEVEL SECURITY;

-- Create policies for the payment_confirmations table
CREATE POLICY "Allow all access to service_role" ON "public"."payment_confirmations" AS PERMISSIVE FOR ALL TO service_role USING (true) WITH CHECK (true);
CREATE POLICY "Allow public insert" ON "public"."payment_confirmations" AS PERMISSIVE FOR INSERT TO anon, authenticated WITH CHECK (true);
