
-- Create the reservations table to store booking and pre-order data
CREATE TABLE IF NOT EXISTS public.reservations (
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    name text NOT NULL,
    phone text NOT NULL,
    guests integer NOT NULL,
    reservation_date timestamp with time zone NOT NULL,
    reservation_time text NOT NULL,
    special_requests text NULL,
    pre_order_total numeric NULL,
    pre_ordered_items jsonb NULL,
    payment_status text NOT NULL DEFAULT 'not_paid'::text,
    checkout_request_id text NULL,
    CONSTRAINT reservations_pkey PRIMARY KEY (id)
);

-- Enable Row-Level Security for the new table
ALTER TABLE public.reservations ENABLE ROW LEVEL SECURITY;

-- Create policies for the reservations table
-- Allow service_role to perform all actions
CREATE POLICY "Allow full access to service_role"
    ON public.reservations
    AS PERMISSIVE
    FOR ALL
    TO service_role
    USING (true)
    WITH CHECK (true);

-- Allow admins to read all reservations
CREATE POLICY "Allow admin read access"
    ON public.reservations
    AS PERMISSIVE
    FOR SELECT
    TO service_role
    USING (true);
