-- Create the payment_confirmations table to store data from the manual M-Pesa submission form.
CREATE TABLE IF NOT EXISTS public.payment_confirmations (
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    mpesa_code text NOT NULL,
    customer_name text NOT NULL,
    customer_phone text NOT NULL,
    payment_time text NOT NULL,
    status text NOT NULL DEFAULT 'pending', -- e.g., 'pending', 'verified', 'invalid'
    CONSTRAINT payment_confirmations_pkey PRIMARY KEY (id)
);

-- Enable Row-Level Security for the new table
ALTER TABLE public.payment_confirmations ENABLE ROW LEVEL SECURITY;

-- Create policies for the table
-- Allow service_role (your server) to perform all actions
CREATE POLICY "Allow full access for service_role"
    ON public.payment_confirmations
    AS PERMISSIVE
    FOR ALL
    TO service_role
    USING (true)
    WITH CHECK (true);

-- Allow authenticated users (e.g., admins) to read all confirmations
CREATE POLICY "Allow read access for authenticated users"
    ON public.payment_confirmations
    AS PERMISSIVE
    FOR SELECT
    TO authenticated
    USING (true);