-- Create the payments table to store M-Pesa transaction data
CREATE TABLE IF NOT EXISTS public.payments (
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    merchant_request_id text NULL,
    checkout_request_id text NULL,
    result_code integer NULL,
    result_desc text NULL,
    amount numeric NULL,
    mpesa_receipt_number text NULL,
    transaction_date timestamp with time zone NULL,
    phone_number text NULL,
    raw_payload jsonb NULL,
    CONSTRAINT payments_pkey PRIMARY KEY (id)
);

-- Enable Row-Level Security for the new table
ALTER TABLE public.payments ENABLE ROW LEVEL SECURITY;

-- Create a policy to allow service_role to perform all actions.
-- This is used by the server-side logic (e.g., Edge Functions, Server Actions)
-- to read and write payment data securely.
CREATE POLICY "Allow full access for service_role"
    ON public.payments
    AS PERMISSIVE
    FOR ALL
    TO service_role
    USING (true)
    WITH CHECK (true);